language: ruby

services:
  - docker

notifications:
  email: false

jobs:
  include:
    - os: linux
      dist: bionic  # 18.04 LTS

      before_install:
      - sudo apt-get -y install python3-pip python3-setuptools
      - pip3 install --upgrade yamllint
      - docker pull docker.io/gnuoctave/octave:6.2.0

      addons:
        apt:
          update: true

      script:
        - 'bash ./assets/ci/run_yamllint.sh'
        - 'bash ./assets/ci/run_bundle.sh'
        - 'docker run -it --volume="$(pwd):/home/packages:rw" gnuoctave/octave:6.2.0 octave --eval "run /home/packages/assets/ci/run_octave.m"'
