title: "GNU Octave - Package extensions index"
description: >-
  Extend GNU Octave's functionality by packages. Find many of them here.
logo: "/assets/octave-logo-512.png"

pkg_icon: "/assets/pkg.png"

exclude:
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - assets/DEVELOPMENT.md
  - assets/travis
