name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check-package:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Pull Octave Docker image
        run: docker pull docker.io/gnuoctave/octave:6.2.0

      - name: Create local package repository
        run: bundle exec jekyll build -d test

      - name: Test package
        run: |
          docker run \
            --volume="$(pwd):/home/jovyan/packages:rw" \
            gnuoctave/octave:6.2.0 \
            octave --eval "cd packages; run assets/ci/run_octave.m"

  check-yaml:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel yamllint

      # FIXME: Remove first line, once the affected file and line number is
      #        visible by default.
      - name: Run yamllint
        run: |
          yamllint --format standard -c ./assets/ci/yamllint.yaml packages
          yamllint -c ./assets/ci/yamllint.yaml packages
